# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
        args: test
      env:
        CI: true
        DB_TYPE: postgres
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: root
        DB_PASSWORD: 123456
        DB_NAME: buscacep
        APP_SECRET: BuscaCep-LuizaLabs
        REDIS_PORT: 6379
        REDIS_HOST: 127.0.0.1
        REDIS_FAMILY: 4
        REDIS_PASSWORD:
        REDIS_NUMBER:
        SENTRY_DNS: 'https://d2c67cceb2b740e9afc69a26c01125f3@o215059.ingest.sentry.io/5678311'
